openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: mchung71@my.bcit.ca

paths:
  /stats:
    get: 
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets UFO sighting and cryptid processed statistics
      responses: 
        '200':
          description: Successfully returned a list of UFO sightings
          content:
            application/json: 
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/SightingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    SightingStats:
      required:
        - num_ufo_sightings
        - max_ufo_num
        - num_cryptid_sightings
        - max_cryptid_num
      properties:
        num_ufo_sightings:
          type: integer
          example: 100
        max_ufo_num:
          type: integer
          example: 5
        num_cryptid_sightings:
          type: integer
          example: 100
        max_cryptid_num:
          type: integer
          example: 5
      type: object